### ISSUE TITLE
fzf-file-widget support

### ISSUE THREAD

**Issue by Luotee** [graahnul-grom/fzf-csh#1]
Hi,
May I ask if you have any plans to add support for the fzf-file-widget function? 
Thank you.

**Comment by graahnul-grom** [comment]
@Luotee
If I understand correctly, you are talking about
file name completion implemented for bash in
[key-bindings.bash](https://github.com/junegunn/fzf/blob/master/shell/key-bindings.bash)
using `find(1)` and activated by pressing `Ctrl + T`.

I never use it, for me built-in file name
completion in `bash` and `csh` is enough.
IMHO, `fzf-file-widget()` has limited usefulness:
there is no filtering, it takes long time to
populate the list; also, it doesn't distinguish
between files and directories.

Nevertheless, you could check out the [tb_0_comp_file_names](https://github.com/graahnul-grom/fzf-csh/tree/tb_0_comp_file_names)
branch, where handling of `Ctrl + T` keys has been added;
it should open an `fzf` list with files and directories
found under the current directory.
Please test it. Will it work for you?

**Comment by L1ttleFlyyy** [comment]
Hi @graahnul-grom 

I wanted to express my genuine appreciation for fzf-csh and your absolutely ingenious solution!
I couldn't find anyone else attempting fzf support for csh, so I thought "just use bindkey to trigger an alias, how hard could it be?" 

Oh boy, was I wrong! I immediately hit csh's brick wall - there's simply **NO way** to programmatically insert text into the command line from key bindings. We tried everything: temp files, command substitution, direct output. Dead ends everywhere.

Then I discovered your `bindkey -s` approach and my jaw dropped. Using tcsh's own key binding system to dynamically create text-injection bindings, then immediately triggering them? That's pure genius! 

The way fzf-csh-impl.csh builds temporary bindkey commands and sources them is an elegant hack that solved what seemed fundamentally impossible. You found THE solution - the ONLY way to modify tcsh's input buffer programmatically.

I'm planning to fork fzf-csh to bypass the `fzf-csh-find.sh` so that I can set my own FZF_DEFAULT_COMMAND, but had to acknowledge the sheer brilliance of your work first!

Thank you for making the impossible possible when everyone else gave up on tcsh!
